/* Nova Lumora niche site engine v1.1 - one config per trade: palette, fonts, layout, signature module, copy. Includes the visit-tracking pixel. */
(function(){
var D=window.NOVA||{},K=D.k||'handyman';
var esc=function(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})};
var tel=String(D.p||'').replace(/\D/g,'');if(tel.length==10)tel='1'+tel;
var pretty=D.pp||(function(){var d=tel.slice(-10);return '('+d.slice(0,3)+') '+d.slice(3,6)+'-'+d.slice(6)})();
var city=D.c||'your area';
var slug=((location.pathname.match(/nova-previews\/([^\/]+)\//)||location.pathname.match(/preview\/([^\/]+)\//)||[])[1])||D.slug||'';
var NOVA_OWNER=false;try{if(/[?&]owner=1/.test(location.search))localStorage.setItem('nova_owner','1');NOVA_OWNER=/[?&]nt=1/.test(location.search)||localStorage.getItem('nova_owner')==='1';}catch(e){}
var PX=NOVA_OWNER?'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==':'https://preview-generator-production-0846.up.railway.app/track/'+encodeURIComponent(slug)+'.gif';
var M={
cleaning:'<svg viewBox="0 0 200 200"><g fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round"><path d="M100 30v40M80 50h40"/><path d="M52 112v26M39 125h26"/><path d="M150 100v22M139 111h22"/></g><circle cx="70" cy="70" r="14" fill="none" stroke="currentColor" stroke-width="4"/><circle cx="140" cy="150" r="20" fill="none" stroke="currentColor" stroke-width="4"/><circle cx="96" cy="152" r="9" fill="currentColor" opacity=".5"/></svg>',
painting:'<svg viewBox="0 0 200 200"><rect x="40" y="40" width="110" height="46" rx="8" fill="currentColor"/><path d="M150 63h22v50h-60v22" fill="none" stroke="currentColor" stroke-width="8" stroke-linejoin="round"/><rect x="100" y="135" width="24" height="44" rx="6" fill="currentColor" opacity=".6"/></svg>',
lawn:'<svg viewBox="0 0 200 200"><circle cx="150" cy="48" r="22" fill="currentColor" opacity=".5"/><g fill="currentColor"><path d="M20 190c6-50 10-80 20-110 4 40 2 80 0 110z"/><path d="M52 190c2-40 8-80 24-124 0 50-4 90-10 124z"/><path d="M90 190c-2-50 6-96 30-134 0 54-6 100-14 134z"/><path d="M128 190c0-40 10-70 28-100 0 40-6 76-14 100z"/><path d="M160 190c2-30 10-50 26-70 0 30-6 52-14 70z"/></g></svg>',
tree:'<svg viewBox="0 0 200 200"><g fill="currentColor"><path d="M100 20L55 85h24L40 140h120l-39-55h24z"/><rect x="90" y="140" width="20" height="46" rx="3"/></g></svg>',
detail:'<svg viewBox="0 0 200 200"><path d="M24 128c0-14 6-22 20-26l22-30c4-5 9-8 16-8h40c8 0 14 3 19 9l22 29c10 3 15 10 15 22v14H24z" fill="currentColor"/><circle cx="64" cy="146" r="16" fill="#0000" stroke="currentColor" stroke-width="8"/><circle cx="144" cy="146" r="16" fill="#0000" stroke="currentColor" stroke-width="8"/><path d="M40 40l30 18M62 28l18 28" stroke="currentColor" stroke-width="5" stroke-linecap="round" opacity=".6"/></svg>',
mechanic:'<svg viewBox="0 0 200 200"><circle cx="100" cy="100" r="44" fill="none" stroke="currentColor" stroke-width="18" stroke-dasharray="18 12"/><circle cx="100" cy="100" r="30" fill="none" stroke="currentColor" stroke-width="10"/><circle cx="100" cy="100" r="10" fill="currentColor"/></svg>',
handyman:'<svg viewBox="0 0 200 200"><path d="M30 98L100 38l70 60v68H30z" fill="none" stroke="currentColor" stroke-width="9" stroke-linejoin="round"/><path d="M72 120l20 20 40-46" fill="none" stroke="currentColor" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/></svg>',
concrete:'<svg viewBox="0 0 200 200"><g fill="currentColor"><rect x="20" y="30" width="76" height="52" rx="4"/><rect x="104" y="30" width="76" height="52" rx="4" opacity=".6"/><rect x="20" y="90" width="52" height="80" rx="4" opacity=".6"/><rect x="80" y="90" width="100" height="80" rx="4"/></g></svg>',
grooming:'<svg viewBox="0 0 200 200"><g fill="currentColor"><ellipse cx="100" cy="132" rx="38" ry="32"/><ellipse cx="50" cy="86" rx="16" ry="22"/><ellipse cx="82" cy="52" rx="16" ry="22"/><ellipse cx="118" cy="52" rx="16" ry="22"/><ellipse cx="150" cy="86" rx="16" ry="22"/></g></svg>',
wash:'<svg viewBox="0 0 200 200"><g fill="currentColor"><path d="M100 24c20 34 40 56 40 82a40 40 0 01-80 0c0-26 20-48 40-82z"/><path d="M162 84c9 16 18 26 18 38a18 18 0 01-36 0c0-12 9-22 18-38z" opacity=".55"/><path d="M38 100c7 12 14 20 14 29a14 14 0 01-28 0c0-9 7-17 14-29z" opacity=".55"/></g></svg>',
junk:'<svg viewBox="0 0 200 200"><g fill="currentColor"><rect x="14" y="62" width="104" height="82" rx="6"/><path d="M126 86h30l28 30v28h-58z" opacity=".7"/><circle cx="52" cy="154" r="16" stroke="#0004" stroke-width="4"/><circle cx="150" cy="154" r="16" stroke="#0004" stroke-width="4"/></g></svg>'};
var N={
cleaning:{lay:'split',f:['Fraunces:opsz,wght@9..144,600;9..144,700','Inter:wght@400;500;600'],hf:"'Fraunces',serif",bf:"'Inter',sans-serif",bg:'#F5FAF8',ink:'#12313A',mut:'#5B7480',ac:'#0E8A8C',ac2:'#F2B544',sf:'#FFFFFF',ln:'#D9E8E5',on:'#fff',hero:'#DDF1EE',
tag:'Home cleaning',h:'A cleaner home in {c}, without lifting a finger.',sub:'Reliable, detail-focused house cleaning on a schedule that fits your life. Tell us about your home and get a quote.',cta:'Get a cleaning quote',
svc:[['Standard cleaning','Kitchens, baths, floors, dusting and the everyday reset.'],['Deep cleaning','Baseboards, inside appliances and the spots a quick clean skips.'],['Move-in / move-out','A fresh start for a new place or a clean handoff.'],['Recurring visits','Weekly, bi-weekly or monthly, the same standard each time.']],
why:[['Same standard every visit','A written checklist so nothing gets missed.'],['Clear, upfront quotes','You know what is included before we start.'],['Easy to reach','Call or text, and we answer in plain English.']],sig:'checklist',pro:[['Tell us about your home','Size, rooms and how often.'],['Get a clear quote','Simple and in writing.'],['Come home to clean','Checklist done, walkthrough ready.']]},
painting:{lay:'bold',f:['DM+Serif+Display','DM+Sans:wght@400;500;700'],hf:"'DM Serif Display',serif",bf:"'DM Sans',sans-serif",bg:'#FBF8F3',ink:'#1C2738',mut:'#66707C',ac:'#C23A2B',ac2:'#2F5D8C',sf:'#FFFFFF',ln:'#E8E1D6',on:'#fff',hero:'#F1E9DC',
tag:'Painting contractor',h:'Paint that looks sharp and stays that way.',sub:'Interior and exterior painting in {c} and nearby. Careful prep, clean lines and a finish you will notice every day.',cta:'Request a free estimate',
svc:[['Interior painting','Walls, ceilings and trim with clean cut-lines.'],['Exterior painting','Siding, doors and trim prepped for the weather.'],['Cabinets & trim','A fresh look without a full remodel.'],['Decks & fences','Stain or paint to protect and refresh.']],
why:[['Prep is the job','Patching, sanding and priming before any color goes on.'],['Tidy crews','Floors and furniture protected, space cleaned up.'],['Walkthrough at the end','We do not leave until you are happy.']],sig:'swatch',pro:[['Walk & estimate','Look at the space, talk colors.'],['Prep & prime','Patch, sand, mask, prime.'],['Paint & finish','Two coats, crisp lines.'],['Final walkthrough','Touch-ups until it is right.']]},
lawn:{lay:'split',f:['Outfit:wght@500;600;700','Inter:wght@400;500'],hf:"'Outfit',sans-serif",bf:"'Inter',sans-serif",bg:'#F6F8EF',ink:'#17331F',mut:'#5E7262',ac:'#1F7A3E',ac2:'#E5A528',sf:'#FFFFFF',ln:'#DCE5CF',on:'#fff',hero:'#E3EFD3',
tag:'Lawn care & landscaping',h:'A lawn the neighbors ask about.',sub:'Mowing, edging and landscape care in {c} and nearby. Dependable visits and a yard that stays sharp all season.',cta:'Get a lawn quote',
svc:[['Mowing & edging','Clean stripes and trimmed edges on a regular schedule.'],['Landscape beds','Mulch, weeding and shaping to keep beds tidy.'],['Seasonal cleanups','Leaves and debris cleared spring and fall.'],['One-time projects','Overgrown lots, hedges and fresh starts.']],
why:[['Show up on schedule','Regular visits so your yard never gets away from you.'],['Straight pricing','A quote you understand before we start.'],['Local and easy to reach','Call or text anytime.']],sig:'seasons',pro:[['Tell us about the yard','Size, access and what you want.'],['Get your quote','Simple recurring or one-time pricing.'],['We handle the rest','Your yard, on autopilot.']]},
tree:{lay:'dark',f:['Barlow+Condensed:wght@600;700;800','Barlow:wght@400;500;600'],hf:"'Barlow Condensed',sans-serif",bf:"'Barlow',sans-serif",bg:'#121C15',ink:'#F1F4EC',mut:'#A2B3A5',ac:'#F28C28',ac2:'#6FB06E',sf:'#1B2A1F',ln:'#2C4032',on:'#161000',dark:1,hero:'#1B2A1F',
tag:'Tree service',h:'Trees handled safely. Yards left clean.',sub:'Tree removal, trimming and storm cleanup in {c} and nearby. Call for an estimate and a straight answer.',cta:'Request an estimate',
svc:[['Tree removal','Planned, controlled removal, including tight spots.'],['Trimming & pruning','Healthier trees and clearer roofs and lines.'],['Storm cleanup','Fallen limbs and trees cleared fast.'],['Stump & brush','Grinding and haul-away so the job is finished.']],
why:[['Safety first','Gear, planning and respect for your property.'],['Cleanup included in the plan','We leave the yard ready to use.'],['Straight estimates','Know the plan and the price up front.']],sig:'alert',pro:[['Call or send photos','Tell us what the tree is doing.'],['Get an estimate','Clear scope and price.'],['Work & cleanup','Done safely, area cleared.']]},
detail:{lay:'dark',f:['Sora:wght@500;600;700','Inter:wght@400;500'],hf:"'Sora',sans-serif",bf:"'Inter',sans-serif",bg:'#0B0D11',ink:'#EEF1F6',mut:'#98A1B0',ac:'#2F8CFF',ac2:'#C9D2E0',sf:'#141821',ln:'#252B38',on:'#fff',dark:1,hero:'#141821',
tag:'Auto detailing',h:'Showroom shine, delivered to your driveway.',sub:'Interior and exterior detailing in {c} and nearby. You pick the package, we bring everything to you.',cta:'Book a detail',
svc:[['Exterior wash & wax','Hand wash, decontamination and protective wax.'],['Interior detail','Vacuum, steam, leather and glass.'],['Full detail','Inside and out, top to bottom.'],['Add-ons','Pet hair, odor treatment and headlight restoration.']],
why:[['We come to you','Home or work, no drop-off needed.'],['Careful technique','Right products for your paint and interior.'],['Before-and-after proof','See the result before you pay.']],sig:'tiers',pro:[['Pick a package','Express, full or showroom.'],['Choose a time','We come to your location.'],['Drive away shining','Walkaround before we leave.']]},
mechanic:{lay:'dark',f:['Oswald:wght@500;600;700','Inter:wght@400;500;600'],hf:"'Oswald',sans-serif",bf:"'Inter',sans-serif",bg:'#1A1E23',ink:'#F4F5F7',mut:'#A4ACB6',ac:'#FFC400',ac2:'#FF6B2C',sf:'#232930',ln:'#363E48',on:'#151100',dark:1,hero:'#232930',
tag:'Mobile mechanic',h:'Car trouble? We come to you.',sub:'Mobile auto repair and diagnostics in {c} and nearby. No tow, no waiting room, just a mechanic at your door.',cta:'Request a repair visit',
svc:[['Diagnostics','Check-engine lights, noises and no-starts figured out.'],['Brakes','Pads, rotors and brake service where you park.'],['Battery & starting','Testing and replacement on-site.'],['Maintenance','Oil, filters, belts and fluids.']],
why:[['No towing needed','Repairs happen at home or work.'],['Straight talk','We explain the problem and the fix.'],['Your time back','No dropping off, no ride home.']],sig:'diag',pro:[['Tell us the problem','Call, text or send a message.'],['We diagnose on-site','At your location.'],['Fix & road-test','Back on the road.']]},
handyman:{lay:'soft',f:['Rubik:wght@500;600;700','Nunito+Sans:wght@400;600'],hf:"'Rubik',sans-serif",bf:"'Nunito Sans',sans-serif",bg:'#FAF6EF',ink:'#1D3557',mut:'#667587',ac:'#E4772C',ac2:'#1D3557',sf:'#FFFFFF',ln:'#EADFCC',on:'#fff',hero:'#FFE9D2',
tag:'Handyman services',h:'The to-do list you never get to? We will.',sub:'Repairs, installs and small projects in {c} and nearby. Send the list, we will get it done.',cta:'Send us your list',
svc:[['Repairs','Doors, drywall, trim, leaks and loose things.'],['Installs & assembly','Fixtures, shelves, TVs and furniture.'],['Small remodel tasks','Tile, paint touch-ups and carpentry.'],['Home maintenance','Seasonal checklists and punch lists.']],
why:[['One call, many jobs','Bundle your list into one visit.'],['Fair, clear pricing','Know the price before we start.'],['Neat and respectful','We treat your home like our own.']],sig:'tasks',pro:[['Send your list','Photos help.'],['Get a quote','By the job or by the hour.'],['We knock it out','One visit where possible.']]},
concrete:{lay:'bold',f:['Archivo:wght@500;700;800','Archivo+Narrow:wght@400;600'],hf:"'Archivo',sans-serif",bf:"'Archivo Narrow',sans-serif",bg:'#EEF0F1',ink:'#22282D',mut:'#5E676F',ac:'#E8541E',ac2:'#3B4249',sf:'#FFFFFF',ln:'#D2D6D9',on:'#fff',hero:'#D8DCDF',
tag:'Concrete contractor',h:'Concrete done right, poured once.',sub:'Driveways, patios, slabs and flatwork in {c} and nearby. Solid prep, clean finishing and a plan that fits your budget.',cta:'Request a concrete quote',
svc:[['Driveways','New pours and replacements with proper base.'],['Patios & walkways','Finished to match your home.'],['Slabs & foundations','Garages, sheds and pads.'],['Repairs & resurfacing','Cracks, spalling and worn surfaces.']],
why:[['Prep makes it last','Grade, base and forms done right.'],['Clear scope and timing','Know the plan before the truck arrives.'],['Clean job site','We leave it ready to use.']],sig:'projects',pro:[['Site visit','Measure, discuss, quote.'],['Prep & form','Grade, base, forms, rebar.'],['Pour & finish','Placed and finished.'],['Cure & clean up','Final walkthrough.']]},
grooming:{lay:'soft',f:['Baloo+2:wght@500;600;700','Nunito:wght@400;600'],hf:"'Baloo 2',sans-serif",bf:"'Nunito',sans-serif",bg:'#FFF7EF',ink:'#3A2A44',mut:'#7C6C88',ac:'#EF6A5B',ac2:'#2DB5A3',sf:'#FFFFFF',ln:'#F2E1D2',on:'#fff',hero:'#FFE3D6',
tag:'Dog grooming',h:'Clean, fluffy and happy pups.',sub:'Gentle grooming in {c} and nearby, with patience and care for every size, shape and personality.',cta:'Book a groom',
svc:[['Bath & brush','Shampoo, blow-dry and a thorough brush-out.'],['Full groom','Bath, haircut, nails and ears.'],['Nails & ears','Quick maintenance between full grooms.'],['Puppy intro','A gentle first groom for new pups.']],
why:[['Gentle handling','Patient, calm and pup-first.'],['Breed-smart cuts','Styles that suit coat and lifestyle.'],['Easy booking','Call or text to set a time.']],sig:'menu',pro:[['Tell us about your dog','Breed, size and temperament.'],['Pick a time','Drop-off or appointment.'],['Pick up a happy pup','Fresh, fluffy and proud.']]},
wash:{lay:'split',f:['Plus+Jakarta+Sans:wght@500;600;700;800','Inter:wght@400;500'],hf:"'Plus Jakarta Sans',sans-serif",bf:"'Inter',sans-serif",bg:'#F4F9FD',ink:'#0F2A43',mut:'#5A7289',ac:'#0A6EBD',ac2:'#37C2C9',sf:'#FFFFFF',ln:'#D6E5F2',on:'#fff',hero:'#DCEEFB',
tag:'Exterior cleaning',h:'Your home’s curb appeal, washed back to life.',sub:'Pressure washing and exterior cleaning in {c} and nearby. See the before-and-after for yourself.',cta:'Get a cleaning quote',
svc:[['House washing','Soft-wash siding to lift dirt, mildew and algae.'],['Driveways & walkways','Concrete cleaned to its original look.'],['Decks, fences & patios','Gentle cleaning that protects the surface.'],['Gutters & windows','Clear gutters and spotless glass.']],
why:[['Right pressure, right surface','Safe methods for siding, wood and concrete.'],['Visible results','Photos before and after.'],['Easy scheduling','Call or text for a quick quote.']],sig:'slider',pro:[['Send photos','Or schedule a quick look.'],['Get a quote','By surface and size.'],['We wash, you admire','Cleaned and rinsed.']]},
junk:{lay:'bold',f:['Bebas+Neue','Barlow:wght@400;500;600'],hf:"'Bebas Neue',sans-serif",bf:"'Barlow',sans-serif",bg:'#FFFBEA',ink:'#17171A',mut:'#5E5E66',ac:'#FFD21F',ac2:'#17171A',sf:'#FFFFFF',ln:'#EDE3B0',on:'#17171A',hero:'#FFEFA1',
tag:'Junk removal',h:'Point at it. We haul it away.',sub:'Junk removal and cleanouts in {c} and nearby. Fast scheduling, careful loading and a swept-clean finish.',cta:'Get a hauling quote',
svc:[['Furniture & appliances','Couches, mattresses, fridges and more.'],['Garage & storage cleanouts','Reclaim the space you have been paying for.'],['Yard waste & debris','Brush, limbs and construction scraps.'],['Estate & move-out','Whole-house or single-room cleanouts.']],
why:[['We do the lifting','You point, we load.'],['Upfront pricing','Know the cost before we haul.'],['Fast scheduling','Call or text for the next open slot.']],sig:'haul',pro:[['Call or text photos','We estimate the load.'],['Pick a time','Quick scheduling.'],['We load & sweep','Gone for good.']]}
};
var C=N[K]||N.handyman,svc=D.s&&D.s.length?D.s:C.svc;
var cl=function(s){return s.replace(/\{c\}/g,esc(city))};
function sig(){var t=C.sig,o='';
if(t=='checklist'){var R=[['Kitchen',['Counters & backsplash','Sink & faucet','Outside of appliances','Floors']],['Bathrooms',['Toilets, tubs & showers','Mirrors & counters','Sinks & fixtures','Floors']],['Living areas',['Dusting surfaces','Vacuuming & mopping','Windowsills','Trash emptied']],['Bedrooms',['Dusting & wiping','Vacuum under reach','Mirrors','Beds made on request']]];
o='<section class="sec"><div class="in"><h2>Room-by-room checklist</h2><p class="lead">Every visit follows a written list, so you always know what is covered. (Sample checklist, customized with you.)</p><div class="grid4">'+R.map(function(r){return '<div class="card"><h3>'+r[0]+'</h3><ul class="ck">'+r[1].map(function(i){return '<li>'+i+'</li>'}).join('')+'</ul></div>'}).join('')+'</div></div></section>'}
if(t=='swatch'){var S=[['Interior','#E9DCC8'],['Exterior','#2F5D8C'],['Cabinets','#8AA38C'],['Trim','#F4F1EA'],['Decks & fences','#9A5B3C'],['Touch-ups','#C23A2B']];
o='<section class="sec"><div class="in"><h2>Pick your finish</h2><p class="lead">From a single accent wall to a whole exterior. Sample swatches shown, color consulting at your estimate.</p><div class="chips">'+S.map(function(s,i){return '<div class="chip" style="--c:'+s[1]+'"><div class="pc"></div><b>'+s[0]+'</b><small>Swatch 0'+(i+1)+'</small></div>'}).join('')+'</div></div></section>'}
if(t=='seasons'){var Q=[['Spring','Cleanup, first mow, fresh mulch'],['Summer','Weekly mowing, edging, weed control'],['Fall','Leaf removal, final mows, beds prepped'],['Winter','Limb cleanup, planning and quotes']];
o='<section class="sec"><div class="in"><h2>A plan for every season</h2><div class="grid4">'+Q.map(function(q,i){return '<div class="card sea s'+i+'"><h3>'+q[0]+'</h3><p>'+q[1]+'</p></div>'}).join('')+'</div></div></section>'}
if(t=='alert'){o='<section class="alert"><div class="in"><b>Storm damage or a tree on the house?</b><span>Call now for urgent help.</span><a class="btn" href="tel:+'+tel+'">'+esc(pretty)+'</a></div></section>'}
if(t=='tiers'){var P=[['Express','Exterior wash, wheels, windows, quick interior wipe.'],['Full detail','Hand wash and wax, deep interior, leather and glass.'],['Showroom','Everything in Full plus decon, clay and sealant, odor treatment.']];
o='<section class="sec"><div class="in"><h2>Choose your package</h2><p class="lead">Pricing shared when you reach out, based on vehicle size and condition.</p><div class="grid3">'+P.map(function(p,i){return '<div class="card tier'+(i==1?' feat':'')+'"><span class="tg">'+(i==1?'Most popular':'Package '+(i+1))+'</span><h3>'+p[0]+'</h3><p>'+p[1]+'</p></div>'}).join('')+'</div></div></section>'}
if(t=='diag'){var Z=['Check-engine light on','Won’t start','Brakes grinding','Battery dead','Strange noise','Overheating','AC not cold','Needs an oil change'];
o='<section class="sec"><div class="in"><h2>What’s going on with your car?</h2><p class="lead">Tap what sounds familiar. We diagnose at your location.</p><div class="pills">'+Z.map(function(z){return '<a class="pill" href="tel:+'+tel+'">'+z+'</a>'}).join('')+'</div></div></section>'}
if(t=='tasks'){var Y=['Fix a leaky faucet','Hang shelves & art','Mount a TV','Patch drywall','Replace a door','Assemble furniture','Install light fixtures','Caulk & seal','Repair trim','Fix a fence gate','Replace outlet covers','Touch-up paint'];
o='<section class="sec"><div class="in"><h2>Your honey-do list, handled</h2><p class="lead">A sample of what customers ask for. If it is not here, ask.</p><div class="pills">'+Y.map(function(z){return '<span class="pill">'+z+'</span>'}).join('')+'</div></div></section>'}
if(t=='projects'){var J=[['Driveways','a'],['Patios','b'],['Walkways','c'],['Slabs','d'],['Steps','e'],['Repairs','f']];
o='<section class="sec"><div class="in"><h2>Projects we pour</h2><div class="grid3">'+J.map(function(j){return '<div class="proj p'+j[1]+'"><b>'+j[0]+'</b><small>Photo slot</small></div>'}).join('')+'</div></div></section>'}
if(t=='menu'){var G=[['Bath & brush','Shampoo, dry, brush-out'],['Full groom','Bath, haircut, nails, ears'],['Nail trim','Quick and gentle'],['De-shed treatment','Less fur on the furniture'],['Teeth & ears','Fresh breath, clean ears'],['Puppy first groom','Slow and sweet']];
o='<section class="sec"><div class="in"><h2>The grooming menu</h2><p class="lead">Pricing depends on breed and coat, ask for a quote.</p><div class="menu">'+G.map(function(g){return '<div class="mi"><b>'+g[0]+'</b><i></i><span>'+g[1]+'</span></div>'}).join('')+'</div></div></section>'}
if(t=='slider'){var Sf=['House siding','Driveways','Decks','Fences','Patios','Roofs & gutters'];
o='<section class="sec"><div class="in"><h2>Dirty to done</h2><p class="lead">Drag to compare. Sample illustration, your real before-and-after photos go here.</p><div class="ba"><div class="b1"></div><div class="b2" id="b2"></div><input id="rg" type="range" min="0" max="100" value="55" aria-label="before after"></div><div class="pills">'+Sf.map(function(z){return '<span class="pill">'+z+'</span>'}).join('')+'</div></div></section>'}
if(t=='haul'){var H=['Couches','Mattresses','Appliances','Yard waste','Construction debris','Garage junk','Old decks & fences','Estate cleanouts'];
o='<section class="sec"><div class="in"><h2>What we haul</h2><div class="grid4">'+H.map(function(h){return '<div class="card hl"><b>'+h+'</b></div>'}).join('')+'</div></div></section>'}
return o}
var css=':root{--bg:'+C.bg+';--ink:'+C.ink+';--mut:'+C.mut+';--ac:'+C.ac+';--ac2:'+C.ac2+';--sf:'+C.sf+';--ln:'+C.ln+';--on:'+C.on+';--hero:'+C.hero+'}'+
'*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 '+C.bf+';padding-top:38px;padding-bottom:64px}h1,h2,h3{font-family:'+C.hf+';line-height:1.08;margin:0}a{color:inherit}.in{max-width:1080px;margin:0 auto;padding:0 20px}'+
'.pv{position:fixed;top:0;left:0;right:0;z-index:50;background:#111;color:#fff;font:600 12px/1.3 Inter,system-ui,sans-serif;text-align:center;padding:10px 12px}.pv a{color:#ffd66b}'+
'header.top{position:sticky;top:38px;z-index:40;background:var(--bg);border-bottom:1px solid var(--ln)}header .in{display:flex;align-items:center;justify-content:space-between;height:62px;gap:12px}.logo{font:700 20px '+C.hf+';letter-spacing:.01em}.logo small{display:block;font:500 11px '+C.bf+';color:var(--mut);letter-spacing:.08em;text-transform:uppercase}'+
'.btn{display:inline-block;background:var(--ac);color:var(--on);font-weight:700;padding:13px 22px;border-radius:999px;text-decoration:none;border:0;cursor:pointer;font-size:16px}.btn.ghost{background:transparent;color:var(--ink);border:2px solid var(--ln)}'+
'.hero{background:var(--hero);padding:56px 0 64px;position:relative;overflow:hidden}.hero .in{display:grid;grid-template-columns:1.15fr .85fr;gap:36px;align-items:center}.eyebrow{display:inline-block;font-weight:700;font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--ac);margin-bottom:12px}'+
'h1{font-size:clamp(36px,6vw,64px)}.hero p{font-size:19px;color:var(--mut);max-width:34em;margin:18px 0 26px}.cta{display:flex;gap:12px;flex-wrap:wrap}.tr{display:flex;gap:8px 18px;flex-wrap:wrap;margin-top:22px;font-size:14px;color:var(--mut)}.tr span:before{content:"\\2713\\00a0";color:var(--ac);font-weight:700}'+
'.art{aspect-ratio:1;border-radius:28px;background:var(--ac);color:var(--on);display:grid;place-items:center;position:relative;box-shadow:0 20px 50px #0003}.art svg{width:62%;opacity:.95}.art:after{content:"Your photo goes here";position:absolute;bottom:14px;left:0;right:0;text-align:center;font:600 11px Inter,sans-serif;opacity:.7;letter-spacing:.06em;text-transform:uppercase}'+
'.sec{padding:60px 0}.sec h2,.svcs h2{font-size:clamp(28px,4vw,40px);margin-bottom:10px}.lead{color:var(--mut);max-width:42em;margin:0 0 26px}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}'+
'.card{background:var(--sf);border:1px solid var(--ln);border-radius:16px;padding:22px}.card h3{font-size:21px;margin-bottom:8px}.card p{margin:0;color:var(--mut)}.ck{list-style:none;padding:0;margin:0}.ck li{padding:6px 0 6px 26px;position:relative;color:var(--mut)}.ck li:before{content:"\\2713";position:absolute;left:0;color:var(--ac);font-weight:700}'+
'.svcs{padding:60px 0;background:var(--sf);border-block:1px solid var(--ln)}.svcs .grid4 .card{background:var(--bg)}.num{font:700 13px '+C.bf+';color:var(--ac);margin-bottom:6px;letter-spacing:.1em}'+
'.why{padding:60px 0}.why .grid3 .card h3{font-size:19px}.pro{padding:60px 0;background:var(--hero)}.stp{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;counter-reset:s}.stp .card:before{counter-increment:s;content:counter(s);display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:var(--ac);color:var(--on);font-weight:700;margin-bottom:12px}'+
'.chips{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:14px}.chip{background:var(--sf);border-radius:10px;overflow:hidden;box-shadow:0 4px 14px #0002}.chip .pc{height:120px;background:var(--c)}.chip b,.chip small{display:block;padding:8px 12px 0}.chip small{padding:0 12px 12px;color:var(--mut);font-size:12px}'+
'.sea{border-top:6px solid var(--ac)}.sea.s1{border-color:#E5A528}.sea.s2{border-color:#C0662A}.sea.s3{border-color:#6B8BA4}.alert{background:var(--ac);color:var(--on)}.alert .in{display:flex;align-items:center;gap:16px;flex-wrap:wrap;padding-block:20px;font-size:18px}.alert .btn{background:#111;color:#fff;margin-left:auto}'+
'.tier .tg{display:inline-block;font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:var(--ac);font-weight:700;margin-bottom:10px}.tier.feat{border-color:var(--ac);box-shadow:0 0 0 2px var(--ac)}.pills{display:flex;flex-wrap:wrap;gap:10px}.pill{background:var(--sf);border:1px solid var(--ln);border-radius:999px;padding:10px 18px;text-decoration:none;font-weight:600}a.pill:hover{border-color:var(--ac)}'+
'.proj{aspect-ratio:4/3;border-radius:14px;padding:16px;display:flex;flex-direction:column;justify-content:flex-end;color:#fff;background:#6b7279;background-image:repeating-linear-gradient(45deg,#fff1 0 2px,#0000 2px 18px),linear-gradient(160deg,#7d858c,#545b61)}.proj b{font:800 24px '+C.hf+'}.proj small{opacity:.7}'+
'.menu{display:grid;grid-template-columns:1fr 1fr;gap:6px 40px}.mi{display:flex;align-items:baseline;gap:8px;padding:10px 0}.mi i{flex:1;border-bottom:2px dotted var(--ln)}.mi span{color:var(--mut);font-size:14px;text-align:right}.hl{display:flex;align-items:center;min-height:90px;border-left:8px solid var(--ac);font:400 24px '+C.hf+'}'+
'.ba{position:relative;height:260px;border-radius:16px;overflow:hidden;margin-bottom:22px;background:linear-gradient(135deg,#6e6b55,#4d4a3a)}.ba .b1{position:absolute;inset:0;background:linear-gradient(135deg,#6e6b55,#4d4a3a)}.ba .b2{position:absolute;inset:0;width:55%;background:linear-gradient(135deg,#dff1fa,#9ed3ee);border-right:3px solid #fff}.ba input{position:absolute;inset:0;width:100%;height:100%;opacity:0;cursor:ew-resize;margin:0}'+
'.stars{color:var(--ac2);font-size:22px;letter-spacing:2px}.rv{padding:60px 0}.info{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding:60px 0}.hrs{list-style:none;padding:0;margin:0}.hrs li{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--ln)}.ph{color:var(--mut);font-size:13px;margin-top:10px}'+
'.quote{padding:64px 0;background:var(--ink);color:var(--bg)}.dark .quote{background:var(--sf);color:var(--ink)}.quote h2{margin-bottom:10px}.quote form{display:grid;gap:12px;max-width:640px;margin-top:20px}.quote input,.quote textarea,.quote select{padding:14px;border-radius:10px;border:1px solid #fff4;background:#fff1;color:inherit;font:inherit}.quote textarea{min-height:90px}.quote .btn{width:fit-content}'+
'footer{padding:28px 0;color:var(--mut);font-size:14px;border-top:1px solid var(--ln)}.callbar{position:fixed;left:0;right:0;bottom:0;z-index:45;background:var(--ac);color:var(--on);text-align:center;font-weight:700;padding:16px;text-decoration:none;display:none}'+
'.bold h1{text-transform:uppercase;letter-spacing:.01em}.bold .hero{background:var(--ac2);color:#fff}.bold .hero p,.bold .tr{color:#fff9}.bold .hero .eyebrow{color:var(--ac)}.bold .hero .btn.ghost{color:#fff;border-color:#fff6}.bold.junk .hero{background:var(--ac);color:var(--ink)}.bold.junk .hero p,.bold.junk .tr{color:#17171Aaa}.bold.junk .art{background:var(--ink);color:var(--ac)}.bold.junk .hero .eyebrow,.bold.junk .tr span:before{color:var(--ink)}.bold.junk .hero .btn{background:var(--ink);color:#fff}.bold.junk .hero .btn.ghost{background:none;color:var(--ink);border-color:#0004}.painting .hero .btn.ghost,.concrete .hero .btn.ghost{color:var(--ink);border-color:#0003}.concrete .hero .eyebrow{color:var(--ac)}'+
'.dark .hero{background:linear-gradient(135deg,var(--hero),var(--bg))}.dark .art{background:radial-gradient(circle at 30% 20%,var(--ac) 0,#0000 70%),var(--sf);color:var(--ac);border:1px solid var(--ln)}.dark .svcs{background:var(--bg)}.dark .svcs .grid4 .card{background:var(--sf)}.dark .pro{background:var(--sf)}.dark .stp .card{background:var(--bg)}.dark h1{letter-spacing:.01em}'+
'.layout-soft .hero .art{border-radius:50% 50% 50% 8%}.layout-soft .hero .in{grid-template-columns:.9fr 1.1fr}.layout-soft .hero .art{order:2;aspect-ratio:1/1.05}.split .art{border-radius:999px 999px 28px 28px}'+
'.concrete .hero{background:linear-gradient(180deg,#D8DCDF,#EEF0F1);color:var(--ink)}.concrete .hero h1{color:var(--ac2)}.concrete .hero p,.concrete .tr{color:var(--mut)}.concrete .art{background:var(--ac2)}.painting .hero{background:#F1E9DC;padding-bottom:84px;color:var(--ink)}.painting .hero:after{content:"";position:absolute;left:0;right:0;bottom:0;height:20px;background:linear-gradient(90deg,#E9DCC8 0 16.6%,#2F5D8C 16.6% 33.3%,#8AA38C 33.3% 50%,#F4F1EA 50% 66.6%,#9A5B3C 66.6% 83.3%,#C23A2B 83.3%)}.painting .hero p,.painting .tr{color:var(--mut)}'+
'@media(max-width:820px){.hero .in,.layout-soft .hero .in,.info{grid-template-columns:1fr}.grid4{grid-template-columns:1fr 1fr}.grid3{grid-template-columns:1fr}.art{max-width:300px}.callbar{display:block}.menu{grid-template-columns:1fr}.hero{padding:36px 0 44px}header .btn{padding:10px 16px;font-size:14px}.sec,.svcs,.why,.pro,.rv,.info,.quote{padding-block:40px}.alert .btn{margin-left:0}}@media(max-width:480px){.grid4{grid-template-columns:1fr}}';
var fonts='https://fonts.googleapis.com/css2?'+C.f.map(function(x){return 'family='+x}).join('&')+'&display=swap';
var h=D.h&&D.h.length?D.h:null,rv=D.r&&D.r[0]?D.r:null;
var hrs=h?'<ul class="hrs">'+h.map(function(l){var i=l.indexOf(':');return '<li><span>'+esc(l.slice(0,i))+'</span><span>'+esc(l.slice(i+1).trim())+'</span></li>'}).join('')+'</ul>':'<ul class="hrs"><li><span>Mon–Fri</span><span>Hours added at launch</span></li><li><span>Sat–Sun</span><span>Hours added at launch</span></li></ul><div class="ph">Placeholder, we will confirm your real hours.</div>';
var rvh=rv?'<div class="card"><div class="stars">★★★★★</div><h3 style="margin-top:8px">'+esc(rv[0].toFixed?rv[0].toFixed(1):rv[0])+' on Google</h3><p>'+esc(rv[1])+' customer reviews. Your best reviews are featured here at launch.</p></div>':'<div class="card"><div class="stars" style="opacity:.35">★★★★★</div><h3 style="margin-top:8px">Customer reviews</h3><p>Real reviews from your happy customers appear here. We never invent them.</p></div>';
var head='<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>'+esc(D.n)+' | '+esc(C.tag)+' in '+esc(city)+' (preview)</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="stylesheet" href="'+fonts+'"><style>'+css+'</style>';
var body='<div class="pv">Preview concept for '+esc(D.n)+' by Nova Lumora. Not a live site. Copy, hours and photos are drafts for your review.</div>'+
'<header class="top"><div class="in"><div class="logo">'+esc(D.n)+'<small>'+esc(C.tag)+' · '+esc(city)+'</small></div><a class="btn" href="tel:+'+tel+'">Call '+esc(pretty)+'</a></div></header>'+
'<section class="hero"><div class="in"><div><span class="eyebrow">'+esc(C.tag)+' in '+esc(city)+'</span><h1>'+cl(C.h)+'</h1><p>'+cl(C.sub)+'</p><div class="cta"><a class="btn" href="#quote">'+esc(C.cta)+'</a><a class="btn ghost" href="tel:+'+tel+'">Call '+esc(pretty)+'</a></div><div class="tr"><span>Serving '+esc(city)+' &amp; nearby</span><span>Call or text for a quote</span><span>Locally run</span></div></div><div class="art">'+M[K]+'</div></div></section>'+
sig()+
'<section class="svcs"><div class="in"><h2>Services</h2><p class="lead">Here is what we can help with.</p><div class="grid4">'+svc.map(function(s,i){return '<div class="card"><div class="num">0'+(i+1)+'</div><h3>'+esc(s[0])+'</h3><p>'+esc(s[1])+'</p></div>'}).join('')+'</div></div></section>'+
'<section class="why"><div class="in"><h2 style="margin-bottom:20px;font-size:clamp(28px,4vw,40px)">Why '+esc(D.n)+'</h2><div class="grid3">'+C.why.map(function(w){return '<div class="card"><h3>'+w[0]+'</h3><p>'+w[1]+'</p></div>'}).join('')+'</div></div></section>'+
'<section class="pro"><div class="in"><h2 style="margin-bottom:20px;font-size:clamp(28px,4vw,40px)">How it works</h2><div class="stp">'+C.pro.map(function(w){return '<div class="card"><h3>'+w[0]+'</h3><p>'+w[1]+'</p></div>'}).join('')+'</div></div></section>'+
'<section class="rv"><div class="in"><h2 style="margin-bottom:20px;font-size:clamp(28px,4vw,40px)">What customers say</h2><div class="grid3">'+rvh+'</div></div></section>'+
'<section><div class="in info"><div><h2 style="font-size:30px;margin-bottom:12px">Hours</h2>'+hrs+'</div><div><h2 style="font-size:30px;margin-bottom:12px">Where we work</h2><p>Serving <b>'+esc(city)+'</b> and surrounding areas.'+(D.a?'<br>'+esc(D.a):'')+'</p><p><a class="btn" href="tel:+'+tel+'">'+esc(pretty)+'</a></p></div></div></section>'+
'<section class="quote" id="quote"><div class="in"><h2>'+esc(C.cta)+'</h2><p>Tell us what you need and we will get back to you.</p><form onsubmit="event.preventDefault();this.querySelector(\'button\').textContent=\'Preview only: the form turns on at launch\'"><input placeholder="Your name"><input placeholder="Phone or email"><textarea placeholder="Tell us about the job"></textarea><button class="btn">Send request</button></form></div></section>'+
'<footer><div class="in">© '+esc(D.n)+' · '+esc(city)+' · <a href="tel:+'+tel+'">'+esc(pretty)+'</a></div></footer><a class="callbar" href="tel:+'+tel+'">Tap to call '+esc(pretty)+'</a><img src="'+PX+'" width="1" height="1" alt="" style="position:absolute;left:-9999px;width:1px;height:1px">';

/* Echo photo pack v1: real trade photography (Unsplash, free licence) in the hero, project tiles, slider and a work gallery.
   Each image is preloaded; if one fails, the original illustration stays. Labeled as sample photos until the owner sends theirs. */
var NOVA_PHOTOS={
 detail:['photo-1601362840469-51e4d8d58785','photo-1520340356584-f9917d1eea6f','photo-1489824904134-891ab64532f1','photo-1605559424843-9e4c228bf1c2','photo-1558618666-fcd25c85cd64','photo-1503376780353-7e6692767b70'],
 mechanic:['photo-1486006920555-c77dcf18193c','photo-1503376780353-7e6692767b70','photo-1489824904134-891ab64532f1','photo-1520340356584-f9917d1eea6f'],
 wash:['photo-1600585154340-be6161a56a0c','photo-1625602812206-5ec545ca1231','photo-1570129477492-45c003edd2be','photo-1600607687939-ce8a6c25118c','photo-1560518883-ce09059eeffa'],
 concrete:['photo-1625602812206-5ec545ca1231','photo-1600585154340-be6161a56a0c','photo-1600607687939-ce8a6c25118c','photo-1560518883-ce09059eeffa'],
 lawn:['photo-1558904541-efa843a96f01','photo-1416879595882-3373a0480b5b','photo-1592150621744-aca64f48394a','photo-1508193638397-1c4234db14d8','photo-1585320806297-9794b3e4eeae'],
 handyman:['photo-1581578731548-c64695cc6952','photo-1504148455328-c376907d081c','photo-1600566752355-35792bedcfea','photo-1562259949-e8e7689d7828'],
 painting:['photo-1562259949-e8e7689d7828','photo-1600566752355-35792bedcfea','photo-1581578731548-c64695cc6952'],
 cleaning:['photo-1600566752355-35792bedcfea','photo-1570129477492-45c003edd2be','photo-1560518883-ce09059eeffa'],
 tree:['photo-1592150621744-aca64f48394a','photo-1508193638397-1c4234db14d8','photo-1558904541-efa843a96f01'],
 junk:['photo-1486406146926-c627a92ad1ab','photo-1581578731548-c64695cc6952'],
 grooming:[]
};
function novaPhotos(k){
 var ids=NOVA_PHOTOS[k]||[]; if(!ids.length) return;
 var U=function(i,w){return 'https://images.unsplash.com/'+i+'?auto=format&fit=crop&w='+(w||1200)+'&q=70'};
 function load(url,cb){var im=new Image();im.onload=function(){cb(url)};im.src=url;}
 var st=document.createElement('style');
 st.textContent='.art.np{background-size:cover!important;background-position:center!important}.art.np svg{display:none}.art.np:after{content:"Sample photo · your work goes here"!important;background:#0008;color:#fff;padding:6px 10px;border-radius:8px;left:12px!important;right:auto!important;bottom:12px!important;opacity:1!important}'+
  '.proj.np{background-size:cover!important;background-position:center!important;text-shadow:0 2px 10px #000a}.proj.np:before{content:"";position:absolute;inset:0;background:linear-gradient(180deg,#0000 40%,#000a);border-radius:inherit}.proj.np{position:relative}.proj.np>*{position:relative}'+
  '.ngal{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px;margin-top:18px}.ngal div{aspect-ratio:4/3;border-radius:14px;background-size:cover;background-position:center;position:relative}'+
  '.ngal div:after{content:"Sample";position:absolute;left:8px;bottom:8px;font:600 10px Inter,sans-serif;background:#0008;color:#fff;padding:3px 7px;border-radius:6px;letter-spacing:.05em;text-transform:uppercase}';
 document.head.appendChild(st);
 var a=document.querySelector('.art'); if(a) load(U(ids[0],1400),function(u){a.style.backgroundImage='url('+u+')';a.classList.add('np')});
 document.querySelectorAll('.proj').forEach(function(p,i){load(U(ids[(i+1)%ids.length],900),function(u){p.style.backgroundImage='url('+u+')';p.classList.add('np')})});
 var b1=document.querySelector('.ba .b1'),b2=document.querySelector('.ba .b2');
 if(b1&&b2) load(U(ids[0],1400),function(u){b1.style.background='url('+u+') center/cover';b1.style.filter='saturate(.25) brightness(.55) sepia(.45)';b2.style.backgroundImage='url('+u+')';b2.style.backgroundSize='cover';b2.style.backgroundPosition='center'});
 var foot=document.querySelector('footer'); if(foot && ids.length>2){
  var sec=document.createElement('section');sec.className='sec';sec.innerHTML='<div class="in"><h2>Recent work</h2><p class="lead">Sample photos. Your own job photos go here once you send them.</p><div class="ngal"></div></div>';
  foot.parentNode.insertBefore(sec,foot); var g=sec.querySelector('.ngal');
  ids.slice(1,4).forEach(function(i){load(U(i,800),function(u){var d=document.createElement('div');d.style.backgroundImage='url('+u+')';g.appendChild(d)})});
 }
}

body+='<script>var NOVA_PHOTOS='+JSON.stringify(NOVA_PHOTOS)+';('+novaPhotos.toString()+')('+JSON.stringify(D.k||'')+')<\/script>';
document.open();document.write('<!doctype html><html lang="en"><head>'+head+'</head><body class="'+C.lay+' '+K+(C.dark?' dark':'')+(C.lay=='soft'?' layout-soft':'')+'">'+body+'</body></html>');document.close();
var rg=document.getElementById('rg'),b2=document.getElementById('b2');if(rg&&b2)rg.oninput=function(){b2.style.width=rg.value+'%'};
})();
